# Generated by Django 2.0.6 on 2019-02-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='checking',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='savings',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
